name: apps_runara
description: "aplikasi"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.0.0
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.1
  google_sign_in: ^7.1.1
  cloud_firestore: ^5.6.12  # Keep the version for Firestore
  flutter_facebook_auth: ^7.1.1
  google_maps_flutter: ^2.8.2
  geolocator: ^14.0.2
  flutter_secure_storage: ^9.2.2
  path_provider: ^2.1.4
  intl: ^0.19.0
  cloud_functions: ^5.0.4
  flutter_markdown: ^0.6.10
  url_launcher: any
  http: ^1.2.0
  shared_preferences: ^2.2.3
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^17.2.1

  firebase_storage: ^12.4.10  # Updated to resolve the conflict
  image_picker: ^0.8.5+3     # Ensure you are using the latest null-safe version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bg_welcome.png
    - assets/img_welcome.png
    - assets/img_welcome2.png
    - assets/ic_back.png
    - assets/bg_space.png
    - assets/img_verify_email.png
    - assets/img_verify_phone.png
    - assets/Img_Home.png
    - assets/icon_help_center.png

